### PR TITLE
:bug: [GCC-10+] Sizeof of State Machine should be minimal

### PR DESCRIPTION
**Pull request by krzysztof-jusiak**
Problem:
- sizeof of `sm` is too big on GCC-10+. It should reflect minimal type which can holde the number of unique states.

Solution:
- Use `[0]` trick for GCC + EBCO to accomplish minimal size.

### CODE REVIEW

**Comment by ooxi** [comment]
I tried building my state machines with this patch and unfortunately still some of my state machines fail to compile while being able to compile fine with GCC 9 and Clang 10:

```
boost/sml.hpp:470:3: error: array subscript 0 is outside array bounds of ‘boost::ext::sml::v1_1_3::aux::zero_wrapper<MyStateMachine::operator()() const [with Configuration = MockConfiguration]::<lambda(MyContext&, MyEvent)>, void> [1]’ [-Werror=array-bounds]
  470 |   zero_wrapper(Ts &&...) {}
      |   ^~~~~~~~~~~~
boost/sml.hpp:1904:71: note: while referencing ‘<anonymous>’
 1904 |     (call<TEvent, args_t<Ts, TEvent>, typename TSM::logger_t>::execute(aux::get_by_id<Ns>(&a), event, sm, deps, subs), ...);
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
boost/sml.hpp:470:3: error: array subscript 0 is outside array bounds of ‘boost::ext::sml::v1_1_3::aux::zero_wrapper<MyStateMachine::operator()() const [with Configuration = MockConfiguration]::<lambda(MyContext&, MyEvent)>, void> [1]’ [-Werror=array-bounds]
  470 |   zero_wrapper(Ts &&...) {}
      |   ^~~~~~~~~~~~
boost/sml.hpp:1904:71: note: while referencing ‘<anonymous>’
 1904 |     (call<TEvent, args_t<Ts, TEvent>, typename TSM::logger_t>::execute(aux::get_by_id<Ns>(&a), event, sm, deps, subs), ...);
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

I can fix this error by omitting [not creating a zero sized array](https://github.com/boost-ext/sml/blob/master/include/boost/sml.hpp#L463)

```
template <class TExpr, class... TArgs>
struct zero_wrapper_impl<TExpr, type_list<TArgs...>> {
  auto operator()(TArgs... args) const { return reinterpret_cast<const TExpr &>(*this)(args...); }
//  __BOOST_SML_ZERO_SIZE_ARRAY(byte);
};
```

However then all `static_assert`s with regards to state machine size fail.


It's incredibly difficult to extract a minimal example of such a state machine, since it seems to only cause problems if the lambda state machine actions reference a method in the provided context object.

Is `__BOOST_SML_ZERO_SIZE_ARRAY(byte)` useful for any functionality or is it just a runtime size optimization?

**Comment by krzysztof-jusiak** [comment]
Hmm, I'm not sure, all tests pass on travis-ci with GCC-10 and I can't find any example which wouldn't work :thinking: 
Maybe you can try to update GCC 10 to 10.3 if you aren't on it?
For the time being, I can provide a macro to disable explicitly zero-size array so that it will be available to opt-out from it.
Something like
```
-D__BOOST_SML_ZERO_SIZE_ARRAY(...)
```
will disable the behaviour
I'd also really, really appreciate any simple example to reproduce the issue, thank you.

**Comment by ooxi** [comment]
> Hmm, I'm not sure, all tests pass on travis-ci with GCC-10 and I can't find any example which wouldn't work thinking
>
> I'd also really, really appreciate any simple example to reproduce the issue, thank you.

yes I feel you. I tried multiple times to extract an example but I always starts compiling again when I comment out seemingly random stuff :/

As soon as I have something tangible I will provide it. Thank you again for your ongoing support.


> Maybe you can try to update GCC 10 to 10.3 if you aren't on it?

I didn't realize GCC 10.3 was already released, I'm still on 10.02; will definitely try upgrading GCC


> For the time being, I can provide a macro to disable explicitly zero-size array so that it will be available to opt-out from it.

That would be great, otherwise I will carry a patch myself

**Comment by krzysztof-jusiak** [comment]
Added `BOOST_SML_CFG_DISABLE_MIN_SIZE` to support the above use-case in https://github.com/boost-ext/sml/pull/381.
By default, the zero-size array is being used to limit the size of the SM.
Fell free to reopen the issue if you find a reproducible small example. I'd really appreciate it, thanks :pray:

**Pull request merged**
