### PR TITLE
Fix issue #384: A regression with anonymous transitions.

### PR DESCRIPTION
**Pull request by Rijom**
Anonymous transition in a nested state are not being executed in absence of an action between the initial state and the anonymous transition. This issue was introduced  with v1.1.3.

Problem:
There is an issue with anonymous transitions not being executed. 

The main loop which processes events is this one:
```
 template <class TEvent, class TDeps, class TSubs>
  bool process_event(const TEvent &event, TDeps &deps, TSubs &subs) {
    bool handled = process_internal_events(event, deps, subs); // <<<< [A]
    do {
      do {
        while (process_internal_events(anonymous{}, deps, subs)) {
        }
      } while (process_defer_events(deps, subs, handled, aux::type<defer_queue_t<TEvent>>{}, events_t{}));
    } while (process_queued_events(deps, subs, aux::type<process_queue_t<TEvent>>{}, events_t{}));
    return handled;
  }

```

Let's look at two cases:
1.  Presence of a on_entry action. See new unit test `subsequent_anonymous_transitions_composite_with_action`.
  Where `bool handled = process_internal_events(event, deps, subs);` will execute the transition from the parent intitial pseudo-state into the composite state. It will then trigger all internal transitions within the composite state.

2. Absence of on_entry action. See new unit test `subsequent_anonymous_transitions_composite_without_action`.
  Here ˜bool handled = process_internal_events(event, deps, subs);`will do nothing. It returns directly with false because the on_entry event is not listed in the transition table. Subsequently `while (process_internal_events(anonymous{}, deps, subs))` will execute an anonymous transition and move from the parent intitial pseudo-state into the composite state **without triggering the composite state's internal transitions, anonymous or otherwise.**

Solution:
I struggle to understand the philosophy here. What's the intended flow? Dunno, please tell me. ;)
My proposed change is to add a special case that treats initial on entry events on case 2. the same as 1.

Issue: #384

Reviewers:
@

### CODE REVIEW

**Comment by Rijom** [comment]
The test fails because it introduces a test that highlights an existing bug. Therefore I think it should be merged. If it is not a real bug, then please let me know why you think so.

I do not know what the root cause of the bug is.

**Comment by GuiCodron** [comment]
This might be an edge case due to the initial event sent at the start of the state machine.

I must have introduced it with the PR that avoided recursive peocessing of anonymous transitions.

If you allow me I will add a fix commit after your tests in your PR.

**Comment by Rijom** [comment]
> If you allow me I will add a fix commit after your tests in your PR.

That would be great!

**Comment by erikzenker** [comment]
Usually you dont merge things that turn the master red. I would suggest to push the fix on that branch, such that test and fix are merged together.

**Comment by Rijom** [comment]
@GuiCodron Any chance for you to fix this? Please let me know if there's anything I can do.

**Pull request merged**
